# Generated by Django 3.1.5 on 2021-02-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
    ]
