# Generated by Django 3.1.5 on 2021-03-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210302_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
