# Generated by Django 3.1.7 on 2021-03-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total',
        ),
    ]
